site_name: Apresentação MKDocs
site_author: A3Data - DashAqui

nav:
  - Home: index.md
  - Pré-Requisitos: requisitos.md


theme:
    name: material

    language: pt
    favicon: "/img/a3_icon.ico"
    logo: "/img/a3_icon.png"
    features: 
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: indigo
        accent: blue
        toggle:
            icon: material/toggle-switch-off-outline
            name: Modo Escuro
      - scheme: slate
        primary: pink
        toggle:
            icon: material/toggle-switch
            name: Modo Claro
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2 # Nível básico dos cabeçalhos
        separator: "_"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
